/**
 * Everything a person reads when the app needs them to do something. Kept in
 * one file so the wording stays consistent and can be translated in one place.
 */

import type { Phase } from "@/lib/phases";

type Role = "ADMIN" | "OFFICIAL" | "JUDGE" | "COACH";

export const ROLE_LABEL: Record<Role, string> = {
  ADMIN: "Administrator",
  OFFICIAL: "Official",
  JUDGE: "Judge",
  COACH: "Coach",
};

const ROLE_WITH_ARTICLE: Record<string, string> = {
  ADMIN: "an administrator",
  OFFICIAL: "an official",
  JUDGE: "a judge",
  COACH: "a coach",
};

export const PHASE_LABEL: Record<Phase, string> = {
  SETUP: "Setup",
  REGISTRATION: "Registration",
  ALLOCATION: "Target allocation",
  QUALIFICATION: "Qualification",
  CUT: "Cut",
  ELIMINATION: "Elimination",
  COMPLETE: "Complete",
};

/** What each role should do in each phase — shown on the tournament overview. */
export const PHASE_HELP: Record<Phase, Partial<Record<"OFFICIAL" | "JUDGE" | "COACH", string>>> = {
  SETUP: {
    OFFICIAL: "Add the categories this event runs in Setup, invite coaches and judges in People, then open registration.",
    COACH: "Registration has not opened yet. You will be able to add archers once it does.",
    JUDGE: "Nothing to do yet. Your targets will be assigned before qualification.",
  },
  REGISTRATION: {
    OFFICIAL: "Coaches are entering archers. When every roster is submitted — or you decide to close it — move to target allocation.",
    COACH: "Add your archers in Roster, check the names, then submit. After you submit you cannot change them.",
    JUDGE: "Nothing to do yet.",
  },
  ALLOCATION: {
    OFFICIAL: "Give every archer a target and position in Allocation, and assign a judge to every target in use (People). Then start qualification.",
    COACH: "Registration is closed. Target assignments will show on your roster.",
    JUDGE: "Check which targets you are assigned to in Scoring.",
  },
  QUALIFICATION: {
    OFFICIAL: "Judges are scoring. Standings update in Results as ends arrive. When every archer has every end, move to the cut.",
    COACH: "Qualification is being shot. Follow the standings in Results.",
    JUDGE: "Score every end for the archers on your targets in Scoring. It works without signal and sends when you are back online.",
  },
  CUT: {
    OFFICIAL: "Check Results for archers level on score, tens and Xs. Record any shoot-off, then start eliminations to draw the bracket.",
    COACH: "Qualification is closed. The bracket will be drawn from the final ranking.",
    JUDGE: "Nothing to score until eliminations start.",
  },
  ELIMINATION: {
    OFFICIAL: "Assign a target to each match in Allocation. When every match is decided, complete the division to award medals.",
    COACH: "Eliminations are being shot. Follow the bracket in Results.",
    JUDGE: "Score the matches on your targets in Scoring, including any shoot-off.",
  },
  COMPLETE: {
    OFFICIAL: "Results are final. Reopen only to correct a mistake — it is recorded with your reason.",
    COACH: "Results are final.",
    JUDGE: "Results are final.",
  },
};

// Suggested category values. Categories are data (CLAUDE.md, locked decision 4):
// the age classes here are the current guess pending Yash's confirmation.
export const CATEGORY_OPTIONS = {
  bow_style: { RECURVE: "Recurve", COMPOUND: "Compound", BAREBOW: "Barebow", INDIAN: "Indian" },
  gender: { M: "Men", W: "Women" },
  age_class: { SUB_JUNIOR: "Sub-junior", CADET: "Cadet", JUNIOR: "Junior", SENIOR: "Senior", MASTER: "Master" },
} as const;

export const guidance = {
  login: {
    title: "Sign in",
    intro:
      "Use the email address your invite was sent to. We will email you a sign-in link and a code. There is no password.",
    emailLabel: "Email address",
    sendButton: "Email me a sign-in link",
    codeSent: (email: string) =>
      `We sent a link and a code to ${email}. Open the link on this device, or type the code here.`,
    codeLabel: "Code from the email",
    verifyButton: "Sign in",
    differentEmail: "Use a different email address",
    invalidEmail: "Enter a full email address, like name@example.com.",
    sendFailed: "The email could not be sent. Wait a minute, then try again.",
    codeRejected: "That code is wrong or has expired. Check the newest email, or start again for a new code.",
  },

  confirm: {
    title: "Finish signing in",
    body: "Tap Continue to finish signing in on this device.",
    button: "Continue",
    failed: "This sign-in link has expired or was already used. Each link works once, for a short time.",
    retry: "Get a new link",
  },

  accept: {
    title: "Join the tournament",
    body: "You have been invited to help run a tournament. Accept to join with the role you were invited for.",
    button: "Accept invite",
    joined: (tournament: string, role: string) =>
      `You have joined ${tournament} as ${ROLE_WITH_ARTICLE[role] ?? role.toLowerCase()}.`,
    open: "Open the tournament",
    signOut: "Sign out",
    errors: {
      invite_not_found:
        "This invite was sent to a different email address. Sign out, then sign in with the address the invite was sent to.",
      invite_expired: "This invite has expired. Ask the tournament official to send you a new one.",
      invite_unavailable: "This invite is no longer active. Ask the tournament official if you still need access.",
      failed: "Something went wrong. Check your connection and try again.",
    } as Record<string, string>,
  },

  nav: {
    home: "My tournaments",
    overview: "Overview",
    setup: "Setup",
    people: "People",
    roster: "Roster",
    allocation: "Allocation",
    score: "Scoring",
    results: "Results",
    publicPage: "Public results page",
    signOut: "Sign out",
  },

  home: {
    intro: "Run a target archery tournament end to end: registration, targets, scoring, the cut, brackets and medals.",
    signIn: "Sign in",
    publicEvents: "Live and recent events",
    noPublicEvents: "No events are published yet.",
    profileTitle: "Your name",
    profileHelp: "Officials see this name next to your email. Add a phone number if you want officials to be able to call you.",
    nameLabel: "Full name",
    phoneLabel: "Phone (optional)",
    saveProfile: "Save",
    yourTournaments: "Your tournaments",
    none: "You are not part of any tournament yet. Open the invite link an official sent you, or start your own below.",
    createTitle: "Start a tournament",
    createHelp: "You become its administrator. Nobody else can see it until you invite them or publish it.",
    tournamentName: "Tournament name",
    venue: "Venue",
    startDate: "First day",
    endDate: "Last day (optional)",
    create: "Create tournament",
  },

  dashboard: {
    yourRole: (role: string) => `You are ${ROLE_WITH_ARTICLE[role] ?? role.toLowerCase()} at this tournament.`,
    divisions: "Divisions",
    noDivisions: "No divisions yet. Officials add them in Setup.",
    archers: (n: number) => (n === 1 ? "1 archer" : `${n} archers`),
    phase: "Phase",
    advanceTo: (phase: string) => `Move to ${phase}`,
    forceClose: "Close registration even if some coaches have not submitted (their archers are locked as entered)",
    reopenTo: (phase: string) => `Reopen ${phase}`,
    reopenReason: "Reason (at least 10 characters, kept in the audit log)",
    whatNext: "What to do now",
  },

  setup: {
    detailsTitle: "Tournament details",
    name: "Name",
    venue: "Venue",
    startDate: "First day",
    endDate: "Last day",
    rulesReference: "Rules reference (AAI circular or WA rulebook edition)",
    published: "Show results on the public page",
    publishedHelp: "Anyone with the link can see names, clubs, targets and scores. Emails and phone numbers are never shown.",
    save: "Save details",
    categoriesTitle: "Categories",
    categoriesHelp:
      "Each category is one competition: bow style, gender and age class, the round it shoots and its match format. A category can be changed or removed only while its division is in Setup.",
    noCategories: "No categories yet.",
    bowStyle: "Bow style",
    gender: "Gender",
    ageClass: "Age class",
    displayName: "Name shown to people (optional)",
    round: "Qualification round",
    matchFormat: "Elimination format",
    bracketSize: "Elimination bracket",
    bracketAuto: "Fit to the field",
    bracketTop: (n: number) => `Top ${n}`,
    add: "Add category",
    remove: "Remove",
    saveBracket: "Save",
  },

  people: {
    membersTitle: "People",
    membersHelp:
      "Everyone who can act in this tournament. An invite link works only for the email it was sent to, so it is safe to share on WhatsApp if the email does not arrive.",
    you: "you",
    status: { INVITED: "Invited", ACTIVE: "Active", REVOKED: "Removed" } as Record<string, string>,
    expires: (date: string) => `link valid until ${date}`,
    inviteLink: "Invite link",
    resend: "Send again",
    revoke: "Remove",
    inviteTitle: "Invite someone",
    email: "Email address",
    role: "Role",
    club: "Club (for coaches)",
    invite: "Send invite",
    judgesTitle: "Judges and targets",
    judgesHelp: "A judge can only score archers and matches on the targets listed here.",
    noJudges: "No targets assigned yet.",
    judge: "Judge",
    targetFrom: "Target",
    targetTo: "to target (optional)",
    assign: "Assign",
    unassign: "Unassign",
    target: (n: number) => `Target ${n}`,
  },

  roster: {
    title: "Your archers",
    help: "Add each archer to the division they compete in. Check names carefully: once you submit a division, only an official can change it.",
    noOpenDivisions: "No division is open for registration right now.",
    none: "No archers yet.",
    name: "Full name",
    club: "Club",
    state: "State",
    division: "Division",
    add: "Add archer",
    save: "Save",
    withdraw: "Withdraw",
    submit: "Submit this division",
    submitHelp: "Submitting locks these archers so officials can allocate targets.",
    submitted: "Submitted",
    draft: "Not submitted",
    target: (bale: number, slot: number) => `Target ${bale}${"ABCDEF"[slot - 1] ?? slot}`,
    importTitle: "Import a list",
    importHelp:
      "Upload a CSV or Excel sheet with columns for name, club, state, bow style, gender and age class — or a PDF entry form. Nothing is added until you review the rows and confirm.",
    file: "File (CSV, XLSX or PDF, up to 4 MB)",
    upload: "Read file",
    batches: "Your imports",
    batchStatus: {
      DRAFT: "Draft",
      PARSING: "Reading…",
      REVIEW: "Ready to review",
      COMMITTED: "Added",
      FAILED: "Discarded or failed",
    } as Record<string, string>,
  },

  imports: {
    title: "Review import",
    parsing: "Reading the file. This page refreshes on its own; it usually takes under a minute.",
    failed: "This import did not complete.",
    committed: (n: number) => `${n} archers were added from this import.`,
    help: "Fix anything flagged, choose a division for every row you keep, then add them. Rows set to Skip are ignored.",
    row: "Row",
    keep: "Add",
    skip: "Skip",
    commit: "Add these archers",
    discard: "Discard import",
    back: "Back to roster",
    chooseDivision: "Choose…",
  },

  allocation: {
    title: "Targets",
    help: "Give every archer a target and position. Auto-assign fills targets four at a time after the highest target already in use.",
    none: "No division is in target allocation.",
    bale: "Target",
    slot: "Position",
    save: "Save",
    auto: "Auto-assign archers without a target",
    unjudged: (bales: number[]) => `No judge assigned to target ${bales.join(", ")}. Assign one in People before starting qualification.`,
    matchesTitle: "Elimination targets",
    matchesHelp: "Matches are scored by the judge of the target set here, or of the first archer's qualification target if none is set.",
    tbd: "to be decided",
  },

  results: {
    title: "Results",
    none: "No results yet.",
    rank: "Rank",
    archer: "Archer",
    club: "Club",
    total: "Total",
    tens: "10s",
    xs: "Xs",
    tie: "tie",
    shootOffTitle: "Ties to resolve",
    shootOffHelp:
      "These archers are level on total, tens and Xs. Enter the order the shoot-off produced (1 = won). It is recorded in the audit log.",
    position: "Place",
    saveShootOff: "Record shoot-off",
    recalculate: "Recalculate standings",
    bracket: "Bracket",
    bye: "bye",
    medal: { GOLD: "Gold", SILVER: "Silver", BRONZE: "Bronze" } as Record<string, string>,
  },

  score: {
    title: "Scoring",
    help: "Tap the arrow values in any order — they are sorted highest first. Ends are kept on this device and sent as soon as there is signal.",
    noTargets: "You have no targets assigned. Ask an official to assign you in People.",
    nothingToScore: "Nothing to score on your targets right now.",
    target: (n: number) => `Target ${n}`,
    endOf: (end: number, total: number) => `End ${end} of ${total}`,
    distance: (m: number) => `${m} m`,
    done: "All ends entered",
    runningTotal: (n: number) => `Total ${n}`,
    undo: "Undo",
    clear: "Clear",
    saveEnd: "Save end",
    back: "Back",
    queued: (n: number) => (n === 1 ? "1 end waiting to send" : `${n} ends waiting to send`),
    allSent: "All ends sent",
    offline: "No signal — ends are saved on this device",
    sendNow: "Send now",
    refused: "Not accepted",
    discard: "Discard",
    matchesTitle: "Matches",
    shootOff: "Shoot-off",
    closestTitle: "Shoot-off arrows are level",
    closestHelp: "Measure which arrow is closer to the centre and record it.",
    closer: (name: string) => `${name} is closer`,
    set: (a: number, b: number) => `Set points ${a}–${b}`,
    points: (a: number, b: number) => `Score ${a}–${b}`,
    endLabel: (n: number) => `End ${n}`,
    shootOffFor: (name: string) => `Shoot-off: ${name}`,
    decided: (name: string) => `Won by ${name}`,
    needsShootOff: "Level — shoot-off needed",
    refusals: {
      duplicate: "This end was already recorded, possibly from another device. Check the scoresheet, then discard this copy.",
      notAllowed: "Not accepted: this archer or match is not on your targets, or the division has moved to another phase.",
      noSuchEnd: "This end does not exist in the round.",
      invalid: (why: string) => `Not accepted: ${why}`,
    },
  },

  display: {
    title: "Live results",
    updated: "Updates about every 30 seconds.",
    qualification: "Qualification",
    bracket: "Bracket",
  },

  ok: {
    profile_saved: "Saved.",
    details_saved: "Tournament details saved.",
    category_added: "Category added.",
    category_removed: "Category removed.",
    bracket_saved: "Bracket size saved.",
    invite_sent: "Invite sent. It is valid for 14 days.",
    invite_saved_email_failed:
      "Invite saved, but the email could not be sent (the email service may be rate-limited). Copy the invite link below and share it directly.",
    revoked: "Removed. They can no longer act in this tournament.",
    assigned: "Targets assigned.",
    unassigned: "Target unassigned.",
    phase_advanced: "Phase changed.",
    phase_reopened: "Phase reopened and recorded in the audit log.",
    archer_added: "Archer added.",
    archer_saved: "Saved.",
    archer_withdrawn: "Archer withdrawn.",
    roster_submitted: "Division submitted.",
    import_discarded: "Import discarded.",
    import_committed: "Archers added.",
    row_saved: "Row saved.",
    target_saved: "Target saved.",
    auto_allocated: "Targets assigned.",
    shoot_off_recorded: "Shoot-off recorded. Standings updated.",
    recalculated: "Standings recalculated.",
    call_recorded: "Recorded.",
  } as Record<string, string>,

  errors: {
    failed: "Something went wrong. Check your connection and try again.",
    not_allowed: "You do not have permission to do that.",
    not_found: "That no longer exists. Refresh the page.",
    invalid_input: "Some fields are missing or not valid. Check them and try again.",
    wrong_phase: "That cannot be done in the division's current phase.",
    phase_changed: "Someone else changed this division's phase a moment ago. Check it and try again.",
    unknown_round: "This category's round or elimination format is not recognised. Fix it in Setup.",
    not_your_target: "That target is not assigned to you.",
    already_member: "That person is already part of this tournament.",
    invalid_email: "Enter a full email address.",
    invalid_role: "Choose a role.",
    invalid_transition: "The division can only move one phase at a time.",
    reason_required: "Write a reason of at least 10 characters. It is kept in the audit log.",
    no_archers: "No archers are entered in this division yet.",
    rosters_not_submitted:
      "Some coaches have not submitted their archers. Wait for them, or tick the box to close registration anyway.",
    archers_without_target: "Some archers have no target or position yet. Finish allocation first.",
    target_without_judge: "A target in use has no judge. Assign one in People first.",
    ends_missing: "Some archers do not have every end recorded yet.",
    shoot_off_required: "Archers inside the bracket are level on everything. Record the shoot-off in Results first.",
    too_few_for_bracket: "A bracket needs at least two archers.",
    matches_not_complete: "Some matches are not decided yet.",
    medals_required: "The final has no winner yet.",
    elimination_already_scored: "Match ends are already recorded, so the bracket cannot be withdrawn.",
    expected_ends_required: "This category's round is not recognised. Fix it in Setup.",
    bracket_required: "The bracket could not be drawn.",
    bracket_archer_outside_division: "The bracket could not be drawn.",
    results_frozen: "Standings are frozen once eliminations start.",
    batch_not_in_review: "This import is not ready to add yet.",
    no_open_division: "A row has no division open for registration. Choose one, or skip the row.",
    unreadable_file: "That file could not be read. Use CSV, XLSX or PDF, up to 4 MB.",
    no_rows: "No archers were found in that file.",
    import_unavailable: "PDF import is not set up on this server yet. Use CSV or Excel.",
    category_in_use: "This category's division has already left Setup, so it cannot be changed.",
    duplicate_category: "That category already exists.",
    duplicate_target: "That judge already has that target.",
    positions_invalid: "Give each archer a different place, starting at 1.",
  } as Record<string, string>,
};
